name: Pull Request CI

on: 
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 13.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    - run: npm run lint
    - run: npm test
      env:
        CI: true

merge: 
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: automerge
      uses: "pascalgn/automerge-action@v0.7.5"
      env:
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

release: 
  runs-on: ubuntu-latest
  needs: merge

  strategy:
    matrix:
      node-version: [13.x]

  steps:
  - uses: actions/checkout@v2
  # git tag to next release 
  - uses: anothrNick/github-tag-action@1.17.3
    id: versionbumper
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      WITH_V: true
  - run: echo ${{ steps.versionbumper.outputs.tag }}
    # - name: Create Release
    #   id: create_release
    #   uses: actions/create-release@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
    #   with:
    #     tag_name: ${{ steps.versionbumper.outputs.tag }}
    #     release_name: Release ${{ steps.versionbumper.outputs.tag }}
    #     draft: false
    #     prerelease: false

    
  # package: 
  #   runs-on: ubuntu-latest
  #   needs: release

  #   strategy:
  #     matrix:
  #       node-version: [13.x]

  #   steps:
  #   - run: echo ${{ steps.versionbumper.outputs.tag }}
    # - uses: actions/checkout@v2
    # - name: Use Node.js ${{ matrix.node-version }}
    #   uses: actions/setup-node@v1
    #   with:
    #     node-version: ${{ matrix.node-version }}
    # - run: npm install
  
