name: Node.js CI

on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 13.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    - run: npm run lint
    - run: npm test
      env:
        CI: true

  # merge: 
  #   runs-on: ubuntu-latest
  #   needs: build

  release: 
    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        node-version: [13.x]

    steps:
    - uses: actions/checkout@v2
    # git tag to next release 
    - uses: anothrNick/github-tag-action@1.17.3
      id: versionbumper
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
    
  package: 
    runs-on: ubuntu-latest
    needs: release

    strategy:
      matrix:
        node-version: [13.x]

    steps:
    - run: echo ${{ steps.versionbumper.output.tag }}
    # - uses: actions/checkout@v2
    # - name: Use Node.js ${{ matrix.node-version }}
    #   uses: actions/setup-node@v1
    #   with:
    #     node-version: ${{ matrix.node-version }}
    # - run: npm install
  
